### ISSUE TITLE
What is DMD ?

### ISSUE THREAD

**Issue by BestStudio** [MicrosoftDocs/SCCMDocs.zh-tw#2]
在這一頁中"重要"的內容裡提要"自 2018 年 8 月 14 日起，混合式行動裝置管理是已被取代的功能。 如需詳細資訊，請參閱什麼是混合式 DMD。"、此內容有誤，應該是"自 2018 年 8 月 14 日起，混合式行動裝置管理是已被取代的功能。 如需詳細資訊，請參閱什麼是混合式 MDM。"

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 09aaf204-6890-76e6-a0fe-e246847c893f
* Version Independent ID: 421111f1-df75-f692-aaeb-e6b5ecfdfe2d
* Content: [混合式 MDM 的新功能 - Configuration Manager](https://docs.microsoft.com/zh-tw/sccm/mdm/understand/whats-new-in-hybrid-mobile-device-management)
* Content Source: [sccm/mdm/understand/whats-new-in-hybrid-mobile-device-management.md](https://github.com/Microsoft/SCCMDocs.zh-tw/blob/live/sccm/mdm/understand/whats-new-in-hybrid-mobile-device-management.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by CeciAc** [comment]
您好，@BestStudio

謝謝您的寶貴意見。  

我們的編審小組審閱了您提出的語言建議，並接受了這些建議。我們已實作您的意見反應並發佈至 Docs 網站上已更新文章的以下頁面 https://docs.microsoft.com/zh-tw/sccm/mdm/understand/whats-new-in-hybrid-mobile-device-management。   

我們由衷感謝您對文章的貢獻，並期望您繼續提供寶貴的意見。  

順頌時祺  

Microsoft DOCS 國際小組
